project_id = "ubccauzshqozoqwhixuk"

[functions.create-order]
verify_jwt = false

[functions.get-orders]
verify_jwt = false

[functions.run-payout-cycle]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false
