project_id = "ubccauzshqozoqwhixuk"

[functions.create-order]
verify_jwt = false

[functions.get-orders]
verify_jwt = false

[functions.run-payout-cycle]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.shop-checkout]
verify_jwt = false

[functions.wallet-ledger]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = false

[functions.bv-expiry-job]
verify_jwt = false

[functions.webhook-gcash]
verify_jwt = false

[functions.webhook-bank]
verify_jwt = false

[functions.webhook-grab]
verify_jwt = false

[functions.webhook-lalamove]
verify_jwt = false
