# Seed data for Terra Farming database
# This file contains the initial product and farm data

SEED_FARMS = [
    {
        "id": "saymayat-vegetable",
        "name": "Saymayat Vegetable Farming",
        "owner": "Denver K. Biang",
        "latitude": 16.455,
        "longitude": 120.587,
        "rating": 4.8,
        "review_count": 94,
        "image": "/images/farms/saymayat.jpg",
        "description": "ATI-certified organic farm in La Trinidad, Benguet. Certificate: LSA-2022-04-058. Specializes in organic highland vegetables using sustainable farming practices passed down through generations of Igorot farming traditions.",
        "products": ["Organic Vegetables", "Cabbage", "Chinese Cabbage", "Baguio Beans", "Carrots"],
        "contact": "0963-791-7097",
        "farm_type": "Organic Farm",
        "certificate": "LSA-2022-04-058",
        "program": "ATI Learning Site",
        "municipality": "La Trinidad",
        "province": "Benguet",
        "elevation": "1,300m above sea level",
        "farm_area": "2.5 hectares",
        "established": "2018",
        "specialties": ["Cold-climate vegetables", "Traditional Igorot organic methods"],
        "categories": ["vegetables"],
        "operating_hours": "6:00 AM – 5:00 PM",
        "delivery_available": True,
        "organic_certified": True,
    },
    {
        "id": "urban-garden-pines",
        "name": "Urban Garden Under the Pines",
        "owner": "George M. Macli-ing",
        "latitude": 16.460,
        "longitude": 120.592,
        "rating": 4.6,
        "review_count": 52,
        "image": "/images/farms/urban-garden.jpg",
        "description": "ATI-certified vegetable farm in La Trinidad, Benguet. Certificate: LSA-2022-04-061. Specializes in highland vegetables and herbs using urban farming techniques under pine forests.",
        "products": ["Highland Vegetables", "Leeks", "Dried Herbs", "Herbs", "Microgreens"],
        "contact": "0921-481-8137",
        "farm_type": "Vegetable Farm",
        "certificate": "LSA-2022-04-061",
        "program": "ATI Learning Site",
        "municipality": "La Trinidad",
        "province": "Benguet",
        "elevation": "1,350m above sea level",
        "farm_area": "1.2 hectares",
        "established": "2019",
        "specialties": ["Herb cultivation", "Urban highland farming"],
        "categories": ["vegetables", "pantry"],
        "operating_hours": "7:00 AM – 5:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
    {
        "id": "la-faustino-farm",
        "name": "La Faustino Farm",
        "owner": "Rebecca R. Faustino",
        "latitude": 16.491,
        "longitude": 120.646,
        "rating": 4.8,
        "review_count": 68,
        "image": "/images/farms/la-faustino.jpg",
        "description": "ATI-certified specialized farm in Tublay, Benguet. Certificate: LSA-2022-04-059. Integrated farm featuring mixed crops, strawberries, and free-range eggs across terraced highland terrain.",
        "products": ["Mixed Crops", "Strawberries", "Bananas", "Pineapple", "Peanut Butter", "Eggs"],
        "contact": "0949-793-4967",
        "farm_type": "Specialized Farm",
        "certificate": "LSA-2022-04-059",
        "program": "ATI Learning Site",
        "municipality": "Tublay",
        "province": "Benguet",
        "elevation": "1,400m above sea level",
        "farm_area": "4.0 hectares",
        "established": "2015",
        "specialties": ["Strawberry cultivation", "Free-range poultry", "Fruit orchards"],
        "categories": ["fruits", "dairy", "pantry"],
        "operating_hours": "6:00 AM – 5:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
    {
        "id": "pcjeam-farm",
        "name": "PCJEAM Farm",
        "owner": "Allison M. Canuto",
        "latitude": 16.580,
        "longitude": 120.676,
        "rating": 4.7,
        "review_count": 45,
        "image": "/images/farms/pcjeam.jpg",
        "description": "ATI-certified specialized farm in Atok, Benguet. Certificate: LSA-2022-06-108. High-altitude vegetable and dairy production at over 2,000m elevation.",
        "products": ["Vegetables", "Potatoes", "Carabao Milk", "Avocado", "Brown Rice"],
        "contact": "0909-201-2105",
        "farm_type": "Specialized Farm",
        "certificate": "LSA-2022-06-108",
        "program": "ATI Learning Site",
        "municipality": "Atok",
        "province": "Benguet",
        "elevation": "2,100m above sea level",
        "farm_area": "5.5 hectares",
        "established": "2014",
        "specialties": ["High-altitude farming", "Potato varieties", "Small-scale dairy"],
        "categories": ["vegetables", "dairy"],
        "operating_hours": "5:30 AM – 4:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
    {
        "id": "dulche-chocolates",
        "name": "Dulche Chocolates Inc.",
        "owner": "Eva Ritchelle Padua",
        "latitude": 16.4023,
        "longitude": 120.596,
        "rating": 4.9,
        "review_count": 112,
        "image": "/images/farms/dulche.jpg",
        "description": "ATI-certified cacao processing facility in Irisan, Baguio City. Specializes in bean-to-bar chocolate using Benguet cacao and locally grown Arabica coffee.",
        "products": ["Cacao", "Artisan Chocolate", "Arabica Coffee", "Tablea"],
        "contact": "0930-296-1654",
        "farm_type": "Cacao Processing",
        "certificate": "LSA-2023-09-216",
        "program": "ATI Learning Site",
        "municipality": "Baguio City",
        "province": "Benguet",
        "elevation": "1,500m above sea level",
        "farm_area": "1.0 hectare",
        "established": "2020",
        "specialties": ["Bean-to-bar chocolate", "Benguet Arabica coffee roasting"],
        "categories": ["pantry"],
        "operating_hours": "8:00 AM – 6:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
    {
        "id": "csb-family-farm",
        "name": "CSB Family Farm",
        "owner": "CSB Family",
        "latitude": 16.389,
        "longitude": 120.571,
        "rating": 4.8,
        "review_count": 86,
        "image": "/images/farms/csb-family.jpg",
        "description": "PhilGAP-certified fruit & vegetable farm in Tuba, Benguet. Implements Philippine Good Agricultural Practices for food safety and quality assurance.",
        "products": ["Vegetables & Fruits", "Sayote", "Calamansi", "Guava", "Kesong Puti", "Muscovado"],
        "farm_type": "Fruit & Vegetable Farm",
        "program": "PhilGAP Certified",
        "municipality": "Tuba",
        "province": "Benguet",
        "elevation": "900m above sea level",
        "farm_area": "3.5 hectares",
        "established": "2016",
        "specialties": ["Artisan dairy products", "Traditional preserves"],
        "categories": ["fruits", "dairy", "pantry"],
        "operating_hours": "6:00 AM – 5:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
    {
        "id": "fit-fab-farm",
        "name": "Fit and Fab Farm",
        "owner": "Fit and Fab Team",
        "latitude": 16.4120,
        "longitude": 120.6010,
        "rating": 4.7,
        "review_count": 64,
        "image": "/images/farms/fit-fab.jpg",
        "description": "PhilGAP-certified organic garden in Lucnab, Baguio City. Produces health-focused organic vegetables with sustainability certification.",
        "products": ["Organic Vegetables", "Pechay", "Lettuce", "Dragon Fruit", "Salad Greens"],
        "farm_type": "Organic Garden",
        "program": "PhilGAP Certified",
        "municipality": "Baguio City",
        "province": "Benguet",
        "elevation": "1,450m above sea level",
        "farm_area": "0.8 hectares",
        "established": "2019",
        "specialties": ["Restaurant-supply greens", "Hydroponic lettuce"],
        "categories": ["vegetables", "fruits"],
        "operating_hours": "7:00 AM – 5:00 PM",
        "delivery_available": True,
        "organic_certified": True,
    },
    {
        "id": "mls-harvest-farm",
        "name": "ML's Harvest Farm",
        "owner": "ML's Harvest Team",
        "latitude": 16.320,
        "longitude": 120.670,
        "rating": 4.6,
        "review_count": 58,
        "image": "/images/farms/mls-harvest.jpg",
        "description": "PhilGAP-certified integrated farm in Itogon, Benguet. Features vegetables, fruit orchards, and honey production.",
        "products": ["Vegetables & Fruits", "Mangoes", "Papayas", "Watermelon", "Wild Honey"],
        "farm_type": "Integrated Farm",
        "program": "PhilGAP Certified",
        "municipality": "Itogon",
        "province": "Benguet",
        "elevation": "800m above sea level",
        "farm_area": "6.0 hectares",
        "established": "2013",
        "specialties": ["Mountain fruit orchards", "Wild honey harvesting"],
        "categories": ["fruits", "dairy", "pantry"],
        "operating_hours": "6:00 AM – 5:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
    {
        "id": "bsu-strawberry-farm",
        "name": "BSU Strawberry Farm",
        "owner": "Benguet State University",
        "latitude": 16.4521,
        "longitude": 120.5823,
        "rating": 4.9,
        "review_count": 245,
        "image": "/images/farms/bsu-strawberry.jpg",
        "description": "The iconic 79-hectare strawberry farm managed by Benguet State University in La Trinidad. A premier agri-tourism destination.",
        "products": ["Strawberries", "Strawberry Jam", "Strawberry Wine", "Fresh Berries"],
        "contact": "074-422-2127",
        "farm_type": "Agri-Tourism Farm",
        "program": "PhilGAP Certified",
        "municipality": "La Trinidad",
        "province": "Benguet",
        "elevation": "1,300m above sea level",
        "farm_area": "79.0 hectares",
        "established": "1987",
        "specialties": ["Pick-your-own strawberries", "Agri-tourism"],
        "categories": ["fruits"],
        "operating_hours": "6:00 AM – 6:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
    {
        "id": "mankayan-root-farm",
        "name": "Mankayan Root Crops Farm",
        "owner": "Julius T. Palicpic",
        "latitude": 16.678,
        "longitude": 120.789,
        "rating": 4.5,
        "review_count": 31,
        "image": "/images/farms/mankayan.jpg",
        "description": "PhilGAP-certified root crop specialist farm in Mankayan, Benguet. Produces high-quality potatoes, carrots, and radish.",
        "products": ["Potatoes", "Carrots", "Radish", "Korean Radish", "Baguio Beans"],
        "contact": "0945-331-7789",
        "farm_type": "Root Crop Farm",
        "program": "PhilGAP Certified",
        "municipality": "Mankayan",
        "province": "Benguet",
        "elevation": "1,600m above sea level",
        "farm_area": "7.0 hectares",
        "established": "2012",
        "specialties": ["Premium root vegetables", "Bulk supply to Metro Manila"],
        "categories": ["vegetables"],
        "operating_hours": "5:00 AM – 4:00 PM",
        "delivery_available": True,
        "organic_certified": False,
    },
]

SEED_PRODUCTS = [
    # Vegetables
    {
        "id": "1",
        "name": "Cabbage (Repolyo)",
        "price": 30.00,
        "unit": "kg",
        "farm_id": "saymayat-vegetable",
        "farm_name": "Saymayat Vegetable Farming",
        "image": "/images/products/cabbage.jpg",
        "category": "Vegetables",
        "stock": 150,
        "organic": True,
        "description": "Fresh highland cabbage from La Trinidad. Crisp and sweet, perfect for salads and stir-fry. Farm wholesale price: ₱25-₱35/kg.",
    },
    {
        "id": "2",
        "name": "Chinese Cabbage",
        "price": 140.00,
        "unit": "kg",
        "farm_id": "saymayat-vegetable",
        "farm_name": "Saymayat Vegetable Farming",
        "image": "/images/products/chinese-cabbage.jpg",
        "category": "Vegetables",
        "stock": 80,
        "organic": True,
        "description": "Tender Chinese cabbage (wombok) grown in Benguet highlands. Great for soups and stir-fries.",
    },
    {
        "id": "3",
        "name": "Baguio Beans",
        "price": 160.00,
        "unit": "kg",
        "farm_id": "saymayat-vegetable",
        "farm_name": "Saymayat Vegetable Farming",
        "image": "/images/products/baguio-beans.jpg",
        "category": "Vegetables",
        "stock": 60,
        "organic": True,
        "description": "Premium Baguio string beans. Crisp and flavorful, harvested at peak freshness.",
    },
    {
        "id": "4",
        "name": "Broccoli",
        "price": 38.00,
        "unit": "kg",
        "farm_id": "fit-fab-farm",
        "farm_name": "Fit and Fab Farm",
        "image": "/images/products/broccoli.jpg",
        "category": "Vegetables",
        "stock": 45,
        "organic": True,
        "description": "Fresh organic broccoli from Fit and Fab Farm. Rich in nutrients.",
    },
    {
        "id": "5",
        "name": "Celery",
        "price": 28.00,
        "unit": "kg",
        "farm_id": "urban-garden-pines",
        "farm_name": "Urban Garden Under the Pines",
        "image": "/images/products/celery.jpg",
        "category": "Vegetables",
        "stock": 70,
        "organic": True,
        "description": "Aromatic Baguio celery. Perfect for soups, salads, and cooking.",
    },
    {
        "id": "6",
        "name": "Potatoes",
        "price": 46.00,
        "unit": "kg",
        "farm_id": "pcjeam-farm",
        "farm_name": "PCJEAM Farm",
        "image": "/images/products/potatoes.jpg",
        "category": "Vegetables",
        "stock": 200,
        "organic": True,
        "description": "Highland potatoes from PCJEAM Farm in Atok. Excellent for any potato dish.",
    },
    {
        "id": "7",
        "name": "Radish",
        "price": 160.00,
        "unit": "kg",
        "farm_id": "mankayan-root-farm",
        "farm_name": "Mankayan Root Crops Farm",
        "image": "/images/products/radish.jpg",
        "category": "Vegetables",
        "stock": 90,
        "organic": True,
        "description": "Fresh organic radish from Mankayan. Crisp and slightly peppery.",
    },
    {
        "id": "8",
        "name": "Cauliflower",
        "price": 12.00,
        "unit": "kg",
        "farm_id": "fit-fab-farm",
        "farm_name": "Fit and Fab Farm",
        "image": "/images/products/cauliflower.jpg",
        "category": "Vegetables",
        "stock": 65,
        "organic": True,
        "description": "White cauliflower from Benguet highlands. Mild and versatile.",
    },
    {
        "id": "9",
        "name": "Sayote (Chayote)",
        "price": 10.00,
        "unit": "kg",
        "farm_id": "csb-family-farm",
        "farm_name": "CSB Family Farm",
        "image": "/images/products/sayote.jpg",
        "category": "Vegetables",
        "stock": 180,
        "organic": True,
        "description": "Fresh sayote from CSB Family Farm. Great for soups and stir-fries.",
    },
    {
        "id": "10",
        "name": "Onion Leeks",
        "price": 28.00,
        "unit": "kg",
        "farm_id": "urban-garden-pines",
        "farm_name": "Urban Garden Under the Pines",
        "image": "/images/products/leeks.jpg",
        "category": "Vegetables",
        "stock": 50,
        "organic": True,
        "description": "Aromatic leeks from Urban Garden. Excellent for soups and garnishing.",
    },
    {
        "id": "11",
        "name": "Baguio Pechay",
        "price": 35.00,
        "unit": "kg",
        "farm_id": "fit-fab-farm",
        "farm_name": "Fit and Fab Farm",
        "image": "/images/products/pechay.jpg",
        "category": "Vegetables",
        "stock": 100,
        "organic": True,
        "description": "Tender Baguio pechay. Quick-cooking leafy green, perfect for stir-fries and soups.",
    },
    {
        "id": "12",
        "name": "Carrots",
        "price": 55.00,
        "unit": "kg",
        "farm_id": "saymayat-vegetable",
        "farm_name": "Saymayat Vegetable Farming",
        "image": "/images/products/carrots.jpg",
        "category": "Vegetables",
        "stock": 120,
        "organic": True,
        "description": "Sweet highland carrots. Naturally sweet and crunchy.",
    },
    {
        "id": "13",
        "name": "Lettuce",
        "price": 85.00,
        "unit": "kg",
        "farm_id": "fit-fab-farm",
        "farm_name": "Fit and Fab Farm",
        "image": "/images/products/lettuce.jpg",
        "category": "Vegetables",
        "stock": 40,
        "organic": True,
        "description": "Fresh iceberg and romaine lettuce. Crisp and refreshing for salads.",
    },
    {
        "id": "14",
        "name": "Tomatoes",
        "price": 40.00,
        "unit": "kg",
        "farm_id": "saymayat-vegetable",
        "farm_name": "Saymayat Vegetable Farming",
        "image": "/images/products/tomatoes.jpg",
        "category": "Vegetables",
        "stock": 130,
        "organic": True,
        "description": "Vine-ripened highland tomatoes. Deep red, juicy, and full of flavor.",
    },
    # Fruits
    {
        "id": "15",
        "name": "Strawberries",
        "price": 350.00,
        "unit": "kg",
        "farm_id": "bsu-strawberry-farm",
        "farm_name": "BSU Strawberry Farm",
        "image": "/images/products/strawberries.jpg",
        "category": "Fruits",
        "stock": 25,
        "organic": True,
        "description": "Sweet strawberries from BSU Farm in La Trinidad. Fresh highland fruit.",
    },
    {
        "id": "16",
        "name": "Carabao Mango",
        "price": 120.00,
        "unit": "kg",
        "farm_id": "mls-harvest-farm",
        "farm_name": "ML's Harvest Farm",
        "image": "/images/products/mangoes.jpg",
        "category": "Fruits",
        "stock": 80,
        "organic": True,
        "description": "Sweet Philippine Carabao mangoes. Known as the world's sweetest mango variety.",
    },
    {
        "id": "17",
        "name": "Papaya",
        "price": 45.00,
        "unit": "kg",
        "farm_id": "mls-harvest-farm",
        "farm_name": "ML's Harvest Farm",
        "image": "/images/products/papayas.jpg",
        "category": "Fruits",
        "stock": 60,
        "organic": True,
        "description": "Fresh ripe papayas. Rich in vitamins A and C, perfect for breakfast.",
    },
    {
        "id": "18",
        "name": "Lakatan Bananas",
        "price": 65.00,
        "unit": "kg",
        "farm_id": "la-faustino-farm",
        "farm_name": "La Faustino Farm",
        "image": "/images/products/bananas.jpg",
        "category": "Fruits",
        "stock": 150,
        "organic": True,
        "description": "Sweet Lakatan bananas. Golden yellow with aromatic flavor.",
    },
    {
        "id": "19",
        "name": "Calamansi",
        "price": 80.00,
        "unit": "kg",
        "farm_id": "csb-family-farm",
        "farm_name": "CSB Family Farm",
        "image": "/images/products/calamansi.jpg",
        "category": "Fruits",
        "stock": 100,
        "organic": True,
        "description": "Fresh Philippine calamansi. Essential for Filipino cooking and juices.",
    },
    {
        "id": "20",
        "name": "Guava",
        "price": 60.00,
        "unit": "kg",
        "farm_id": "csb-family-farm",
        "farm_name": "CSB Family Farm",
        "image": "/images/products/guava.jpg",
        "category": "Fruits",
        "stock": 70,
        "organic": True,
        "description": "Fresh Philippine guava. Sweet and aromatic, rich in Vitamin C.",
    },
    {
        "id": "21",
        "name": "Dragon Fruit",
        "price": 180.00,
        "unit": "kg",
        "farm_id": "fit-fab-farm",
        "farm_name": "Fit and Fab Farm",
        "image": "/images/products/dragon-fruit.jpg",
        "category": "Fruits",
        "stock": 30,
        "organic": True,
        "description": "Fresh dragon fruit (pitaya). Beautiful pink skin with white flesh, rich in antioxidants.",
    },
    {
        "id": "22",
        "name": "Avocado",
        "price": 90.00,
        "unit": "kg",
        "farm_id": "pcjeam-farm",
        "farm_name": "PCJEAM Farm",
        "image": "/images/products/avocado.jpg",
        "category": "Fruits",
        "stock": 45,
        "organic": True,
        "description": "Creamy highland avocados from PCJEAM Farm. Buttery texture, perfect for shakes.",
    },
    # Dairy & Eggs
    {
        "id": "23",
        "name": "Fresh Farm Eggs",
        "price": 8.00,
        "unit": "pc",
        "farm_id": "la-faustino-farm",
        "farm_name": "La Faustino Farm",
        "image": "/images/products/fresh-eggs.jpg",
        "category": "Dairy & Eggs",
        "stock": 500,
        "organic": True,
        "description": "Free-range farm eggs. Rich golden yolks, freshly collected daily.",
    },
    {
        "id": "24",
        "name": "Carabao Milk",
        "price": 120.00,
        "unit": "L",
        "farm_id": "pcjeam-farm",
        "farm_name": "PCJEAM Farm",
        "image": "/images/products/carabao-milk.jpg",
        "category": "Dairy & Eggs",
        "stock": 30,
        "organic": True,
        "description": "Fresh carabao milk. Creamier and richer than cow's milk.",
    },
    {
        "id": "25",
        "name": "Kesong Puti",
        "price": 180.00,
        "unit": "250g",
        "farm_id": "csb-family-farm",
        "farm_name": "CSB Family Farm",
        "image": "/images/products/kesong-puti.jpg",
        "category": "Dairy & Eggs",
        "stock": 25,
        "organic": True,
        "description": "Traditional Filipino white cheese made from carabao milk. Perfect with pandesal.",
    },
    {
        "id": "26",
        "name": "Salted Duck Eggs",
        "price": 15.00,
        "unit": "pc",
        "farm_id": "mls-harvest-farm",
        "farm_name": "ML's Harvest Farm",
        "image": "/images/products/salted-eggs.jpg",
        "category": "Dairy & Eggs",
        "stock": 200,
        "organic": False,
        "description": "Itlog na maalat - traditional salted duck eggs. Rich orange yolk.",
    },
    # Pantry
    {
        "id": "27",
        "name": "Benguet Arabica Coffee",
        "price": 450.00,
        "unit": "250g",
        "farm_id": "dulche-chocolates",
        "farm_name": "Dulche Chocolates Inc.",
        "image": "/images/products/arabica-coffee.jpg",
        "category": "Pantry",
        "stock": 40,
        "organic": True,
        "description": "Premium Cordillera Arabica coffee beans. Grown at high altitude with rich, smooth flavor.",
    },
    {
        "id": "28",
        "name": "Wild Honey",
        "price": 380.00,
        "unit": "500ml",
        "farm_id": "mls-harvest-farm",
        "farm_name": "ML's Harvest Farm",
        "image": "/images/products/wild-honey.jpg",
        "category": "Pantry",
        "stock": 25,
        "organic": True,
        "description": "Pure wild honey from Itogon. Raw and unfiltered, rich in natural enzymes.",
    },
    {
        "id": "29",
        "name": "Muscovado Sugar",
        "price": 95.00,
        "unit": "500g",
        "farm_id": "csb-family-farm",
        "farm_name": "CSB Family Farm",
        "image": "/images/products/muscovado.jpg",
        "category": "Pantry",
        "stock": 80,
        "organic": True,
        "description": "Unrefined muscovado sugar. Dark, rich molasses flavor, traditionally processed.",
    },
    {
        "id": "30",
        "name": "Tablea (Cacao Tablets)",
        "price": 200.00,
        "unit": "200g",
        "farm_id": "dulche-chocolates",
        "farm_name": "Dulche Chocolates Inc.",
        "image": "/images/products/tablea.jpg",
        "category": "Pantry",
        "stock": 50,
        "organic": True,
        "description": "Traditional Filipino cacao tablea. Pure roasted cacao discs for tsokolate.",
    },
    {
        "id": "31",
        "name": "Organic Brown Rice",
        "price": 85.00,
        "unit": "kg",
        "farm_id": "pcjeam-farm",
        "farm_name": "PCJEAM Farm",
        "image": "/images/products/brown-rice.jpg",
        "category": "Pantry",
        "stock": 100,
        "organic": True,
        "description": "Organic brown rice from PCJEAM Farm. Unpolished whole grain with high fiber.",
    },
    {
        "id": "32",
        "name": "Coconut Vinegar (Sukang Tuba)",
        "price": 65.00,
        "unit": "350ml",
        "farm_id": "mls-harvest-farm",
        "farm_name": "ML's Harvest Farm",
        "image": "/images/products/coconut-vinegar.jpg",
        "category": "Pantry",
        "stock": 70,
        "organic": True,
        "description": "Traditional coconut sap vinegar. Naturally fermented, essential for Filipino cooking.",
    },
]
